### ISSUE TITLE
Is it allowed to use an empty string for BAT_RSPEC_FLAGS

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry-incubator/bosh-cpi-certification#6]
https://github.com/cloudfoundry-incubator/bosh-cpi-certification/blob/master/shared/tasks/run-bats.sh#L9 doesn't allow an empty string.

**Comment by dpb587-pivotal** [comment]
I think all CPIs currently rely on a specific set of flags. Are you running all BATs tests with a CPI that can run every BATs test? Feel free to make a PR if you're finding it should not be a required variable.
