### ISSUE TITLE
director-vars doesn't have the execute permission

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry-incubator/bosh-cpi-certification#7]
https://github.com/cloudfoundry-incubator/bosh-cpi-certification/blob/master/azure/assets/director-vars doesn't have the execute permission, so the error is thrown:
```
pipelines/shared/tasks/prepare-director.sh: line 12: pipelines/azure/assets/director-vars: Permission denied
```

**Comment by dpb587-pivotal** [comment]
Fixed - thanks!
